# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

mod_version=1.12

# Minecraft Version Information
minecraft_version=1.21.1
minecraft_range=[1.21.1,1.21.2)

# NeoForge Version Information
loader_range=[4,)
neoforge_version=21.1.219
neoforge_range=[21.1,21.2)
parchment_minecraft=1.21
parchment_version=2024.07.28

# Build dependencies
jei_version=19.8.+
